#
# Spring Boot 配置
spring:
  #
  # 数据库 配置
  datasource:
    #
    # 多数据源
    #
    # 没有@DS	      默认数据源
    # @DS("dsName")	  dsName可以为组名也可以为具体某个库的名称
    # 可以注解在方法上,可以注解在service实现或mapper接口方法上。
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      primary: master
      datasource:
        # 主数据源
        master:
          # 测试驱动（非打包时使用）
          # com.mysql.cj.jdbc.Driver
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          # 测试 URL（非打包时使用）
          url: jdbc:p6spy:mysql://127.0.0.1:3306/spring_boot_quartz?useSSL=false&serverTimezone=GMT%2B8
          # 用户名
          username: root
          # 密码
          password: root
    #
    # Hikari 连接池
    hikari:
      # 最小空闲连接数量
      minimum-idle: 3
      # 连接池最大连接数
      maximum-pool-size: 10
