SELECT
    qjd.SCHED_NAME,
    qjd.JOB_NAME,
    qjd.JOB_GROUP,
    qjd.DESCRIPTION,
    qjd.JOB_CLASS_NAME,
    qjd.IS_DURABLE,
    qjd.IS_NONCONCURRENT,
    qjd.IS_UPDATE_DATA,
    qjd.REQUESTS_RECOVERY,
    qjd.JOB_DATA,

    qt.SCHED_NAME AS qt_SCHED_NAME,
    qt.TRIGGER_NAME AS qt_TRIGGER_NAME,
    qt.TRIGGER_GROUP AS qt_TRIGGER_GROUP,
    qt.JOB_NAME AS qt_JOB_NAME,
    qt.JOB_GROUP AS qt_JOB_GROUP,
    qt.DESCRIPTION AS qt_DESCRIPTION,
    qt.NEXT_FIRE_TIME AS qt_NEXT_FIRE_TIME,
    qt.PREV_FIRE_TIME AS qt_PREV_FIRE_TIME,
    qt.PRIORITY AS qt_PRIORITY,
    qt.TRIGGER_STATE AS qt_TRIGGER_STATE,
    qt.TRIGGER_TYPE AS qt_TRIGGER_TYPE,
    qt.START_TIME AS qt_START_TIME,
    qt.END_TIME AS qt_END_TIME,
    qt.CALENDAR_NAME AS qt_CALENDAR_NAME,
    qt.MISFIRE_INSTR AS qt_MISFIRE_INSTR,
    qt.JOB_DATA AS qt_JOB_DATA,

    qct.SCHED_NAME AS qct_SCHED_NAME,
    qct.TRIGGER_NAME AS qct_TRIGGER_NAME,
    qct.TRIGGER_GROUP AS qct_TRIGGER_GROUP,
    qct.CRON_EXPRESSION AS qct_CRON_EXPRESSION,
    qct.TIME_ZONE_ID AS qct_TIME_ZONE_ID,

    qft.SCHED_NAME AS qft_SCHED_NAME,
    qft.ENTRY_ID AS qft_ENTRY_ID,
    qft.TRIGGER_NAME AS qft_TRIGGER_NAME,
    qft.TRIGGER_GROUP AS qft_TRIGGER_GROUP,
    qft.INSTANCE_NAME AS qft_INSTANCE_NAME,
    qft.FIRED_TIME AS qft_FIRED_TIME,
    qft.SCHED_TIME AS qft_SCHED_TIME,
    qft.PRIORITY AS qft_PRIORITY,
    qft.STATE AS qft_STATE,
    qft.JOB_NAME AS qft_JOB_NAME,
    qft.JOB_GROUP AS qft_JOB_GROUP,
    qft.IS_NONCONCURRENT AS qft_IS_NONCONCURRENT,
    qft.REQUESTS_RECOVERY AS qft_REQUESTS_RECOVERY
FROM
    qrtz_job_details AS qjd
LEFT JOIN qrtz_triggers AS qt ON qjd.SCHED_NAME = qt.SCHED_NAME
    AND qjd.JOB_NAME = qt.JOB_NAME
    AND qjd.JOB_GROUP = qt.JOB_GROUP
LEFT JOIN qrtz_cron_triggers AS qct ON qct.SCHED_NAME = qt.SCHED_NAME
    AND qct.TRIGGER_NAME = qt.TRIGGER_NAME
    AND qct.TRIGGER_GROUP = qt.TRIGGER_GROUP
LEFT JOIN qrtz_fired_triggers AS qft ON qft.SCHED_NAME = qjd.SCHED_NAME
    AND qft.JOB_NAME = qjd.JOB_NAME
    AND qft.JOB_GROUP = qjd.JOB_GROUP
    AND qft.TRIGGER_NAME = qt.TRIGGER_NAME
    AND qft.TRIGGER_GROUP = qt.TRIGGER_GROUP
